version: 2.1
jobs:
  test:
    docker:
      - image: node:16.0.0
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            npm i
            npm run test
